"""FastAPI app exposing the PlateLoc service over the lab status spec v1.1.

Endpoints
---------

Spec-mandated (always available):

* ``GET /``         - cheap probe: ``ProbeResponse``
* ``GET /health``   - liveness: ``HealthResponse``
* ``GET /status``   - full ``EquipmentStatus`` envelope (side-effect-free)
* ``GET /openapi.json`` - generated by FastAPI

Claim protocol (NEW in v1.1; required to issue other /control/* calls
when ``enforce_claims=True``):

* ``POST /control/claim``     - body: ``ClaimRequest``;  -> ``ClaimResponse``
* ``POST /control/heartbeat`` - header ``X-Claim-Token``; -> ``ClaimResponse``
* ``POST /control/release``   - header ``X-Claim-Token``; -> 204

Control (optional in the spec, useful for an operator UI). Each call
requires ``X-Claim-Token: <claim_token>`` matching the live claim, or
the device returns HTTP 423.

* ``POST /control/startup``          - body: ``{profile?}``
* ``POST /control/shutdown``         - disconnect
* ``POST /control/seal/temperature`` - body: ``{temperature_c}``
* ``POST /control/seal/time``        - body: ``{seconds}``
* ``POST /control/seal/start``       - body: ``{temperature_c?, seconds?}``
* ``POST /control/seal/stop``
* ``POST /control/stage/in``
* ``POST /control/stage/out``

Auth: none at the device level; access is gated by Tailscale ACLs.
The claim protocol provides *coordination*, not authentication.
CORS: wildcard by default; tighten via ``[service] cors_origins`` in
``config.toml`` if the device ever leaves the Tailnet.
"""

from __future__ import annotations

import asyncio
import logging
from contextlib import asynccontextmanager
from typing import Annotated, Any

from fastapi import Depends, FastAPI, Header, HTTPException, Request, Response
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field

from . import config as _config
from .claims import ClaimConflict, UnknownClaim
from .models import (
    PROTOCOL_VERSION,
    ClaimRejection,
    ClaimRequest,
    ClaimResponse,
    EquipmentStatus,
    HealthResponse,
    ProbeResponse,
)
from .service import PlateLocService

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Request/response bodies for /control/*
# ---------------------------------------------------------------------------


class StartupRequest(BaseModel):
    profile: str | None = Field(
        default=None,
        description="Profile name as configured in the PlateLoc Diagnostics dialog.",
    )


class SetSealingTemperatureRequest(BaseModel):
    temperature_c: int = Field(ge=20, le=235, description="Sealing setpoint, 20-235 C.")


class SetSealingTimeRequest(BaseModel):
    seconds: float = Field(ge=0.5, le=12.0, description="Cycle duration, 0.5-12.0 s.")


class SealStartRequest(BaseModel):
    """Configure (optional) and start a seal cycle in one call."""

    temperature_c: int | None = Field(default=None, ge=20, le=235)
    seconds: float | None = Field(default=None, ge=0.5, le=12.0)


class CommandResponse(BaseModel):
    ok: bool = True
    message: str | None = None


# ---------------------------------------------------------------------------
# Internal exception used to send a top-level claim-related error body
# (per STATUS_SPEC v1.1). FastAPI's ``HTTPException`` always wraps the
# detail in ``{"detail": ...}``; the v1.1 spec requires the rejection
# body to sit *at the top level* (so ``claimed_by`` and ``retry_after_s``
# parse cleanly with ``response.json()["claimed_by"]``).
# ---------------------------------------------------------------------------


class _ClaimResponseException(Exception):
    """Raised when the API needs to emit a top-level JSON body with a
    custom HTTP status. Caught by the registered exception handler."""

    def __init__(
        self,
        status_code: int,
        payload: dict[str, Any],
        headers: dict[str, str] | None = None,
    ) -> None:
        super().__init__(f"HTTP {status_code}")
        self.status_code = status_code
        self.payload = payload
        self.headers = headers or {}


# ---------------------------------------------------------------------------
# App factory
# ---------------------------------------------------------------------------


def create_app(
    *,
    dry_run: bool | None = None,
    enforce_claims: bool | None = None,
) -> FastAPI:
    """Build the FastAPI application.

    Parameters
    ----------
    dry_run:
        Force dry-run mode regardless of ``config.toml``. ``None`` means
        "use the config file". Tests pass ``True`` to keep CI hardware-free.
    enforce_claims:
        Strict v1.1 enforcement of ``X-Claim-Token`` on ``/control/*``.
        ``None`` means "use the config file" (default ``True``). Set
        ``False`` for v1.1 *advisory* deployments where the device
        publishes ``allowed_actions`` and ``details.claimed_by`` but
        does not block writes from clients without a token.
    """

    if dry_run is None:
        dry_run = bool(_config.get("service", "dry_run", False))
    if enforce_claims is None:
        enforce_claims = bool(_config.get("service", "enforce_claims", True))

    service = PlateLocService(dry_run=dry_run, enforce_claims=enforce_claims)
    startup_timeout = float(_config.get("service", "startup_connect_timeout_s", 15.0))

    @asynccontextmanager
    async def lifespan(app: FastAPI):  # noqa: ARG001
        # Best-effort connect on startup. If the device is unreachable
        # (powered off, COM port busy, ActiveX not registered) we log and
        # leave the service in `requires_init`; the operator can retry
        # via POST /control/startup.
        try:
            await asyncio.wait_for(service.startup(), timeout=startup_timeout)
            logger.info("PlateLoc auto-connect succeeded")
        except asyncio.TimeoutError:
            logger.warning(
                "PlateLoc connect timed out after %.0fs; leaving in requires_init",
                startup_timeout,
            )
        except Exception as exc:
            logger.warning("PlateLoc auto-connect failed: %s", exc)
        try:
            yield
        finally:
            # Defensive: drop any active claim before tearing the driver
            # down so a crashed orchestrator cannot prevent the next
            # process restart from accepting a fresh claim.
            try:
                await service.claims.force_clear()
            except Exception:
                logger.exception("Error while clearing claim on shutdown")
            await service.shutdown()

    app = FastAPI(
        title="Agilent PlateLoc Sealer API",
        version="1.1.0",
        description=(
            "REST API for the Agilent PlateLoc Thermal Microplate Sealer. "
            "Conforms to the AC lab equipment status spec v1.1 - see the "
            "`docs/STATUS_SPEC.md` and `docs/STATUS_SPEC_v1_1.md` documents "
            "in the ac-organic-lab monorepo."
        ),
        lifespan=lifespan,
    )

    cors_origins: Any = _config.get("service", "cors_origins", ["*"])
    app.add_middleware(
        CORSMiddleware,
        allow_origins=list(cors_origins),
        allow_credentials=False,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    @app.exception_handler(_ClaimResponseException)
    async def _claim_response_handler(
        request: Request, exc: _ClaimResponseException
    ) -> JSONResponse:  # noqa: ARG001
        return JSONResponse(
            status_code=exc.status_code,
            content=exc.payload,
            headers=exc.headers,
        )

    # ---- Spec endpoints ---------------------------------------------------

    @app.get("/", response_model=ProbeResponse, tags=["spec"])
    async def probe() -> ProbeResponse:
        return ProbeResponse(
            equipment_id=service.equipment_id,
            equipment_name=service.equipment_name,
            protocol_version=PROTOCOL_VERSION,
        )

    @app.get("/health", response_model=HealthResponse, tags=["spec"])
    async def health() -> HealthResponse:
        return HealthResponse()

    @app.get("/status", response_model=EquipmentStatus, tags=["spec"])
    async def status() -> EquipmentStatus:
        return await service.get_status()

    # ---- Claim protocol (v1.1) -------------------------------------------

    async def require_claim(
        x_claim_token: Annotated[str | None, Header(alias="X-Claim-Token")] = None,
    ) -> None:
        """Gate every ``/control/*`` request with the live claim token.

        Returns ``None`` (i.e. is a no-op) when the service was built
        with ``enforce_claims=False``: in that mode the device runs the
        v1.1 claim protocol in *advisory* mode - it still issues tokens
        and publishes ``claimed_by`` on ``/status`` but does not block
        clients that omit the header.
        """
        if not service.enforce_claims:
            return
        if x_claim_token is None or not await service.claims.validate(x_claim_token):
            current = await service.claims.current()
            payload: dict[str, Any] = {
                "detail": (
                    "missing or invalid X-Claim-Token; POST /control/claim first"
                ),
                "claimed_by": (
                    current.model_dump(mode="json") if current is not None else None
                ),
                "retry_after_s": None,
            }
            raise _ClaimResponseException(status_code=423, payload=payload)

    @app.post(
        "/control/claim",
        response_model=ClaimResponse,
        responses={409: {"model": ClaimRejection}},
        tags=["claim"],
    )
    async def control_claim(req: ClaimRequest) -> ClaimResponse:
        try:
            return await service.claims.acquire(req)
        except ClaimConflict as exc:
            rejection = ClaimRejection(
                detail=str(exc),
                claimed_by=exc.claimed_by,
                retry_after_s=exc.retry_after_s,
            )
            # Per STATUS_SPEC v1.1 the rejection body must sit at the top
            # level of the response so ``response.json()["claimed_by"]``
            # works without unwrapping. We emit Retry-After alongside the
            # JSON ``retry_after_s`` so non-SDK clients can use either.
            raise _ClaimResponseException(
                status_code=409,
                payload=rejection.model_dump(mode="json"),
                headers={"Retry-After": str(int(exc.retry_after_s + 1))},
            )

    @app.post(
        "/control/heartbeat",
        response_model=ClaimResponse,
        tags=["claim"],
    )
    async def control_heartbeat(
        x_claim_token: Annotated[str | None, Header(alias="X-Claim-Token")] = None,
    ) -> ClaimResponse:
        try:
            return await service.claims.heartbeat(x_claim_token)
        except UnknownClaim:
            raise HTTPException(
                status_code=401,
                detail="claim token is unknown or expired; POST /control/claim",
            )

    @app.post(
        "/control/release",
        status_code=204,
        tags=["claim"],
    )
    async def control_release(
        x_claim_token: Annotated[str | None, Header(alias="X-Claim-Token")] = None,
    ) -> Response:
        await service.claims.release(x_claim_token)
        return Response(status_code=204)

    # ---- Control endpoints (optional per spec) ---------------------------

    @app.post("/control/startup", response_model=CommandResponse, tags=["control"])
    async def control_startup(
        req: StartupRequest,
        _claim: None = Depends(require_claim),
    ) -> CommandResponse:
        try:
            await service.startup(profile=req.profile)
        except Exception as exc:
            raise HTTPException(status_code=503, detail=str(exc))
        return CommandResponse(ok=True, message="Connected")

    @app.post("/control/shutdown", response_model=CommandResponse, tags=["control"])
    async def control_shutdown(
        _claim: None = Depends(require_claim),
    ) -> CommandResponse:
        await service.shutdown()
        return CommandResponse(ok=True, message="Disconnected")

    @app.post(
        "/control/seal/temperature",
        response_model=CommandResponse,
        tags=["control"],
    )
    async def control_seal_temperature(
        req: SetSealingTemperatureRequest,
        _claim: None = Depends(require_claim),
    ) -> CommandResponse:
        try:
            await service.set_sealing_temperature(req.temperature_c)
        except RuntimeError as exc:
            raise HTTPException(status_code=409, detail=str(exc))
        except Exception as exc:
            raise HTTPException(status_code=500, detail=str(exc))
        return CommandResponse(message=f"Set sealing temperature to {req.temperature_c} C")

    @app.post(
        "/control/seal/time",
        response_model=CommandResponse,
        tags=["control"],
    )
    async def control_seal_time(
        req: SetSealingTimeRequest,
        _claim: None = Depends(require_claim),
    ) -> CommandResponse:
        try:
            await service.set_sealing_time(req.seconds)
        except RuntimeError as exc:
            raise HTTPException(status_code=409, detail=str(exc))
        except Exception as exc:
            raise HTTPException(status_code=500, detail=str(exc))
        return CommandResponse(message=f"Set sealing time to {req.seconds} s")

    @app.post(
        "/control/seal/start",
        response_model=CommandResponse,
        tags=["control"],
    )
    async def control_seal_start(
        req: SealStartRequest,
        _claim: None = Depends(require_claim),
    ) -> CommandResponse:
        try:
            if req.temperature_c is not None:
                await service.set_sealing_temperature(req.temperature_c)
            if req.seconds is not None:
                await service.set_sealing_time(req.seconds)
            await service.start_cycle()
        except RuntimeError as exc:
            raise HTTPException(status_code=409, detail=str(exc))
        except Exception as exc:
            raise HTTPException(status_code=500, detail=str(exc))
        return CommandResponse(message="Seal cycle started")

    @app.post(
        "/control/seal/stop",
        response_model=CommandResponse,
        tags=["control"],
    )
    async def control_seal_stop(
        _claim: None = Depends(require_claim),
    ) -> CommandResponse:
        try:
            await service.stop_cycle()
        except RuntimeError as exc:
            raise HTTPException(status_code=409, detail=str(exc))
        except Exception as exc:
            raise HTTPException(status_code=500, detail=str(exc))
        return CommandResponse(message="Seal cycle stopped")

    @app.post(
        "/control/stage/in",
        response_model=CommandResponse,
        tags=["control"],
    )
    async def control_stage_in(
        _claim: None = Depends(require_claim),
    ) -> CommandResponse:
        try:
            await service.move_stage_in()
        except RuntimeError as exc:
            raise HTTPException(status_code=409, detail=str(exc))
        except Exception as exc:
            raise HTTPException(status_code=500, detail=str(exc))
        return CommandResponse(message="Stage moving in")

    @app.post(
        "/control/stage/out",
        response_model=CommandResponse,
        tags=["control"],
    )
    async def control_stage_out(
        _claim: None = Depends(require_claim),
    ) -> CommandResponse:
        try:
            await service.move_stage_out()
        except RuntimeError as exc:
            raise HTTPException(status_code=409, detail=str(exc))
        except Exception as exc:
            raise HTTPException(status_code=500, detail=str(exc))
        return CommandResponse(message="Stage moving out")

    # Expose service for tests/debugging.
    app.state.service = service
    return app


__all__ = ["create_app"]
