"""FastAPI app exposing the PlateLoc service over the lab status spec v1.0.

Endpoints
---------

Spec-mandated (always available):

* ``GET /``         - cheap probe: ``ProbeResponse``
* ``GET /health``   - liveness: ``HealthResponse``
* ``GET /status``   - full ``EquipmentStatus`` envelope (side-effect-free)
* ``GET /openapi.json`` - generated by FastAPI

Control (optional in the spec, useful for an operator UI later):

* ``POST /control/startup``         - connect; body: ``{profile?}``
* ``POST /control/shutdown``        - disconnect
* ``POST /control/seal/temperature`` - body: ``{temperature_c}``
* ``POST /control/seal/time``       - body: ``{seconds}``
* ``POST /control/seal/start``      - body: ``{temperature_c?, seconds?}``
* ``POST /control/seal/stop``
* ``POST /control/stage/in``
* ``POST /control/stage/out``

Auth: none at the device level; access is gated by Tailscale ACLs.
CORS: wildcard by default; tighten via ``[service] cors_origins`` in
``config.toml`` if the device ever leaves the Tailnet.
"""

from __future__ import annotations

import asyncio
import logging
from contextlib import asynccontextmanager
from typing import Any

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from . import config as _config
from .models import (
    PROTOCOL_VERSION,
    EquipmentStatus,
    HealthResponse,
    ProbeResponse,
)
from .service import PlateLocService

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Request/response bodies for /control/*
# ---------------------------------------------------------------------------


class StartupRequest(BaseModel):
    profile: str | None = Field(
        default=None,
        description="Profile name as configured in the PlateLoc Diagnostics dialog.",
    )


class SetSealingTemperatureRequest(BaseModel):
    temperature_c: int = Field(ge=20, le=235, description="Sealing setpoint, 20-235 C.")


class SetSealingTimeRequest(BaseModel):
    seconds: float = Field(ge=0.5, le=12.0, description="Cycle duration, 0.5-12.0 s.")


class SealStartRequest(BaseModel):
    """Configure (optional) and start a seal cycle in one call."""

    temperature_c: int | None = Field(default=None, ge=20, le=235)
    seconds: float | None = Field(default=None, ge=0.5, le=12.0)


class CommandResponse(BaseModel):
    ok: bool = True
    message: str | None = None


# ---------------------------------------------------------------------------
# App factory
# ---------------------------------------------------------------------------


def create_app(*, dry_run: bool | None = None) -> FastAPI:
    """Build the FastAPI application.

    Parameters
    ----------
    dry_run:
        Force dry-run mode regardless of ``config.toml``. ``None`` means
        "use the config file". Tests pass ``True`` to keep CI hardware-free.
    """

    if dry_run is None:
        dry_run = bool(_config.get("service", "dry_run", False))

    service = PlateLocService(dry_run=dry_run)
    startup_timeout = float(_config.get("service", "startup_connect_timeout_s", 15.0))

    @asynccontextmanager
    async def lifespan(app: FastAPI):  # noqa: ARG001
        # Best-effort connect on startup. If the device is unreachable
        # (powered off, COM port busy, ActiveX not registered) we log and
        # leave the service in `requires_init`; the operator can retry
        # via POST /control/startup.
        try:
            await asyncio.wait_for(service.startup(), timeout=startup_timeout)
            logger.info("PlateLoc auto-connect succeeded")
        except asyncio.TimeoutError:
            logger.warning(
                "PlateLoc connect timed out after %.0fs; leaving in requires_init",
                startup_timeout,
            )
        except Exception as exc:
            logger.warning("PlateLoc auto-connect failed: %s", exc)
        try:
            yield
        finally:
            await service.shutdown()

    app = FastAPI(
        title="Agilent PlateLoc Sealer API",
        version="1.0.0",
        description=(
            "REST API for the Agilent PlateLoc Thermal Microplate Sealer. "
            "Conforms to the AC lab equipment status spec v1.0 - see the "
            "`docs/STATUS_SPEC.md` document in the ac-organic-dashboard repo."
        ),
        lifespan=lifespan,
    )

    cors_origins: Any = _config.get("service", "cors_origins", ["*"])
    app.add_middleware(
        CORSMiddleware,
        allow_origins=list(cors_origins),
        allow_credentials=False,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    # ---- Spec endpoints ---------------------------------------------------

    @app.get("/", response_model=ProbeResponse, tags=["spec"])
    async def probe() -> ProbeResponse:
        return ProbeResponse(
            equipment_id=service.equipment_id,
            equipment_name=service.equipment_name,
            protocol_version=PROTOCOL_VERSION,
        )

    @app.get("/health", response_model=HealthResponse, tags=["spec"])
    async def health() -> HealthResponse:
        return HealthResponse()

    @app.get("/status", response_model=EquipmentStatus, tags=["spec"])
    async def status() -> EquipmentStatus:
        return await service.get_status()

    # ---- Control endpoints (optional per spec) ---------------------------

    @app.post("/control/startup", response_model=CommandResponse, tags=["control"])
    async def control_startup(req: StartupRequest) -> CommandResponse:
        try:
            await service.startup(profile=req.profile)
        except Exception as exc:
            raise HTTPException(status_code=503, detail=str(exc))
        return CommandResponse(ok=True, message="Connected")

    @app.post("/control/shutdown", response_model=CommandResponse, tags=["control"])
    async def control_shutdown() -> CommandResponse:
        await service.shutdown()
        return CommandResponse(ok=True, message="Disconnected")

    @app.post(
        "/control/seal/temperature",
        response_model=CommandResponse,
        tags=["control"],
    )
    async def control_seal_temperature(
        req: SetSealingTemperatureRequest,
    ) -> CommandResponse:
        try:
            await service.set_sealing_temperature(req.temperature_c)
        except RuntimeError as exc:
            raise HTTPException(status_code=409, detail=str(exc))
        except Exception as exc:
            raise HTTPException(status_code=500, detail=str(exc))
        return CommandResponse(message=f"Set sealing temperature to {req.temperature_c} C")

    @app.post(
        "/control/seal/time",
        response_model=CommandResponse,
        tags=["control"],
    )
    async def control_seal_time(req: SetSealingTimeRequest) -> CommandResponse:
        try:
            await service.set_sealing_time(req.seconds)
        except RuntimeError as exc:
            raise HTTPException(status_code=409, detail=str(exc))
        except Exception as exc:
            raise HTTPException(status_code=500, detail=str(exc))
        return CommandResponse(message=f"Set sealing time to {req.seconds} s")

    @app.post(
        "/control/seal/start",
        response_model=CommandResponse,
        tags=["control"],
    )
    async def control_seal_start(req: SealStartRequest) -> CommandResponse:
        try:
            if req.temperature_c is not None:
                await service.set_sealing_temperature(req.temperature_c)
            if req.seconds is not None:
                await service.set_sealing_time(req.seconds)
            await service.start_cycle()
        except RuntimeError as exc:
            raise HTTPException(status_code=409, detail=str(exc))
        except Exception as exc:
            raise HTTPException(status_code=500, detail=str(exc))
        return CommandResponse(message="Seal cycle started")

    @app.post(
        "/control/seal/stop",
        response_model=CommandResponse,
        tags=["control"],
    )
    async def control_seal_stop() -> CommandResponse:
        try:
            await service.stop_cycle()
        except RuntimeError as exc:
            raise HTTPException(status_code=409, detail=str(exc))
        except Exception as exc:
            raise HTTPException(status_code=500, detail=str(exc))
        return CommandResponse(message="Seal cycle stopped")

    @app.post(
        "/control/stage/in",
        response_model=CommandResponse,
        tags=["control"],
    )
    async def control_stage_in() -> CommandResponse:
        try:
            await service.move_stage_in()
        except RuntimeError as exc:
            raise HTTPException(status_code=409, detail=str(exc))
        except Exception as exc:
            raise HTTPException(status_code=500, detail=str(exc))
        return CommandResponse(message="Stage moving in")

    @app.post(
        "/control/stage/out",
        response_model=CommandResponse,
        tags=["control"],
    )
    async def control_stage_out() -> CommandResponse:
        try:
            await service.move_stage_out()
        except RuntimeError as exc:
            raise HTTPException(status_code=409, detail=str(exc))
        except Exception as exc:
            raise HTTPException(status_code=500, detail=str(exc))
        return CommandResponse(message="Stage moving out")

    # Expose service for tests/debugging.
    app.state.service = service
    return app


__all__ = ["create_app"]
